# Apify

In [32]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [33]:
df_associate = pd.read_csv("../data/raw/Apify/dataset_linkedin-jobs-scraper_associate.csv")
df_director = pd.read_csv("../data/raw/Apify/dataset_linkedin-jobs-scraper_director.csv")
df_entry = pd.read_csv("../data/raw/Apify/dataset_linkedin-jobs-scraper_entry.csv")
df_intership = pd.read_csv("../data/raw/Apify/dataset_linkedin-jobs-scraper_intership.csv")
df_mid = pd.read_csv("../data/raw/Apify/dataset_linkedin-jobs-scraper_mid.csv")

In [34]:
df_apify = pd.concat([df_associate,df_director,df_entry,df_intership,df_mid], axis=0)

In [35]:
df_apify.head()

,title,location,postedTime,publishedAt,jobUrl,companyName,companyUrl,description,applicationsCount,contractType,experienceLevel,workType,sector,salary,posterFullName,posterProfileUrl,companyId,applyUrl,applyType,benefits
0,"Málaga Cabin Crew Opportunities (Dubai Based, ...",Greater Málaga Metropolitan Area,1 week ago,2026-02-11,https://es.linkedin.com/jobs/view/m%C3%A1laga-...,Emirates,https://ae.linkedin.com/company/emirates?trk=p...,"Job Purpose\n\nA personality that shines, the ...",59 applicants,Full-time,Associate,"Customer Service, General Business, and Other",Airlines and Aviation and Hospitality,NaN,NaN,NaN,5042.0,https://es.linkedin.com/jobs/view/m%C3%A1laga-...,EASY_APPLY,NaN
1,Junior Dirección General,"Barcelona, Catalonia, Spain",2 weeks ago,2026-02-03,https://es.linkedin.com/jobs/view/junior-direc...,Catalonia Hotels & Resorts,https://es.linkedin.com/company/cataloniahotel...,Si te apasiona el mundo de los viajes y deseas...,Over 200 applicants,Full-time,Associate,Business Development,Hospitality,NaN,NaN,NaN,74645.0,https://es.linkedin.com/jobs/view/junior-direc...,EASY_APPLY,NaN
2,Auxiliar administrativo,"Yaiza, Canary Islands, Spain",1 day ago,2026-02-23,https://es.linkedin.com/jobs/view/auxiliar-adm...,Hoteles Elba | Hotels & Resorts,https://es.linkedin.com/company/elba-hoteles?t...,Desde el Hotel Elba Lanzarote Royal Village Re...,38 applicants,Full-time,Associate,"Customer Service, Human Resources, and Adminis...","Hospitality, Accommodation and Food Services, ...",NaN,NaN,NaN,2224474.0,https://es.linkedin.com/jobs/view/auxiliar-adm...,EASY_APPLY,NaN
3,Profesorado Refuerzo Educativo,"Madrid, Community of Madrid, Spain",2 weeks ago,2026-02-05,https://es.linkedin.com/jobs/view/profesorado-...,JC Madrid Deporte y Cultura SL,https://es.linkedin.com/company/jc-madrid-depo...,Tareas\n\n\nImpartir refuerzo educativo a alum...,30 applicants,Contract,Associate,Education,Education Administration Programs,€9.00/hr - €9.90/hr,NaN,NaN,2778391.0,https://es.linkedin.com/jobs/view/profesorado-...,EASY_APPLY,NaN
4,Autor/a de contenidos eLearning profesional,Spain,4 weeks ago,2026-01-26,https://es.linkedin.com/jobs/view/autor-a-de-c...,ADR Formación,https://es.linkedin.com/company/adr-formacion?...,"Buscamos personas apasionadas, comprometidas, ...",Over 200 applicants,Contract,Associate,Education,E-Learning Providers,NaN,NaN,NaN,2471496.0,https://join.com/companies/adrformacion/155713...,EXTERNAL,NaN

In [36]:
df_apify.isnull().sum()

title                  27
location               27
postedTime             27
publishedAt             2
jobUrl                 27
companyName            33
companyUrl             32
description            27
applicationsCount      27
contractType           27
experienceLevel        27
workType               27
sector                 36
salary               3705
posterFullName       3464
posterProfileUrl     3464
companyId              32
applyUrl               27
applyType               0
benefits             3954
dtype: int64

In [37]:
df_apify.shape

(3954, 20)

In [38]:
df_apify.drop(columns=['benefits','posterProfileUrl','posterFullName','jobUrl','companyUrl','applyUrl','applyType'],inplace=True)

In [39]:
df_apify.head()

,title,location,postedTime,publishedAt,companyName,description,applicationsCount,contractType,experienceLevel,workType,sector,salary,companyId
0,"Málaga Cabin Crew Opportunities (Dubai Based, ...",Greater Málaga Metropolitan Area,1 week ago,2026-02-11,Emirates,"Job Purpose\n\nA personality that shines, the ...",59 applicants,Full-time,Associate,"Customer Service, General Business, and Other",Airlines and Aviation and Hospitality,NaN,5042.0
1,Junior Dirección General,"Barcelona, Catalonia, Spain",2 weeks ago,2026-02-03,Catalonia Hotels & Resorts,Si te apasiona el mundo de los viajes y deseas...,Over 200 applicants,Full-time,Associate,Business Development,Hospitality,NaN,74645.0
2,Auxiliar administrativo,"Yaiza, Canary Islands, Spain",1 day ago,2026-02-23,Hoteles Elba | Hotels & Resorts,Desde el Hotel Elba Lanzarote Royal Village Re...,38 applicants,Full-time,Associate,"Customer Service, Human Resources, and Adminis...","Hospitality, Accommodation and Food Services, ...",NaN,2224474.0
3,Profesorado Refuerzo Educativo,"Madrid, Community of Madrid, Spain",2 weeks ago,2026-02-05,JC Madrid Deporte y Cultura SL,Tareas\n\n\nImpartir refuerzo educativo a alum...,30 applicants,Contract,Associate,Education,Education Administration Programs,€9.00/hr - €9.90/hr,2778391.0
4,Autor/a de contenidos eLearning profesional,Spain,4 weeks ago,2026-01-26,ADR Formación,"Buscamos personas apasionadas, comprometidas, ...",Over 200 applicants,Contract,Associate,Education,E-Learning Providers,NaN,2471496.0

In [40]:
df_apify.to_csv('../data/raw/apify.csv',  index=False)

# Glassdoor

In [41]:
from glob import glob #libreria que se puede utilizar para listar los archivos de una carpeta

In [42]:
files = glob('../data/raw/glassdoor_parciales/*.csv')
data_path = "../data/raw/glassdoor_parciales\\"

for f in files:
    print(f)

../data/raw/glassdoor_parciales\ciudad_Barcelona.csv
../data/raw/glassdoor_parciales\ciudad_Valencia.csv
../data/raw/glassdoor_parciales\ciudad_Sevilla.csv
../data/raw/glassdoor_parciales\ciudad_Zaragoza.csv
../data/raw/glassdoor_parciales\ciudad_Málaga.csv
../data/raw/glassdoor_parciales\ciudad_Murcia.csv
../data/raw/glassdoor_parciales\ciudad_Bilbao.csv
../data/raw/glassdoor_parciales\ciudad_Alicante.csv
../data/raw/glassdoor_parciales\ciudad_Valladolid.csv
../data/raw/glassdoor_parciales\ciudad_Palma-de-Mallorca.csv
../data/raw/glassdoor_parciales\ciudad_Las-Palmas-de-Gran-Canaria.csv
../data/raw/glassdoor_parciales\ciudad_San_Sebastián.csv
../data/raw/glassdoor_parciales\ciudad_A-Coruña.csv
../data/raw/glassdoor_parciales\ciudad_Granada.csv
../data/raw/glassdoor_parciales\ciudad_Vigo.csv
../data/raw/glassdoor_parciales\ciudad_Córdoba.csv
../data/raw/glassdoor_parciales\ciudad_Santander.csv
../data/raw/glassdoor_parciales\ciudad_Pamplona.csv
../data/raw/glassdoor_parciales\ciudad_Oviedo.csv
../data/raw/glassdoor_parciales\ciudad_Gijón.csv
../data/raw/glassdoor_parciales\ciudad_Vitoria.csv
../data/raw/glassdoor_parciales\ciudad_Santa-Cruz-de-Tenerife.csv
../data/raw/glassdoor_parciales\ciudad_Salamanca.csv
../data/raw/glassdoor_parciales\ciudad_Burgos.csv
../data/raw/glassdoor_parciales\ciudad_Cádiz.csv
../data/raw/glassdoor_parciales\ciudad_Tarragona.csv
../data/raw/glassdoor_parciales\ciudad_León.csv
../data/raw/glassdoor_parciales\ciudad_Jerez-de-la-Frontera.csv
../data/raw/glassdoor_parciales\ciudad_Castellón-de-la-Plana.csv
../data/raw/glassdoor_parciales\puesto_Tecnología.csv
../data/raw/glassdoor_parciales\puesto_Sanidad.csv
../data/raw/glassdoor_parciales\ciudad_Albacete.csv
../data/raw/glassdoor_parciales\ciudad_Almería.csv
../data/raw/glassdoor_parciales\ciudad_Ávila.csv
../data/raw/glassdoor_parciales\ciudad_Badajoz.csv
../data/raw/glassdoor_parciales\ciudad_Cáceres.csv
../data/raw/glassdoor_parciales\ciudad_Ciudad-Real.csv
../data/raw/glassdoor_parciales\ciudad_Cuenca.csv
../data/raw/glassdoor_parciales\ciudad_Girona.csv
../data/raw/glassdoor_parciales\ciudad_Guadalajara.csv
../data/raw/glassdoor_parciales\ciudad_Huelva.csv
../data/raw/glassdoor_parciales\ciudad_Huesca.csv
../data/raw/glassdoor_parciales\ciudad_Jaén.csv
../data/raw/glassdoor_parciales\ciudad_Logroño.csv
../data/raw/glassdoor_parciales\ciudad_Lleida.csv
../data/raw/glassdoor_parciales\ciudad_Lugo.csv
../data/raw/glassdoor_parciales\ciudad_Ourense.csv
../data/raw/glassdoor_parciales\ciudad_Palencia.csv
../data/raw/glassdoor_parciales\ciudad_Pontevedra.csv
../data/raw/glassdoor_parciales\ciudad_Segovia.csv
../data/raw/glassdoor_parciales\ciudad_Soria.csv
../data/raw/glassdoor_parciales\ciudad_Teruel.csv
../data/raw/glassdoor_parciales\ciudad_Toledo.csv
../data/raw/glassdoor_parciales\ciudad_Zamora.csv
../data/raw/glassdoor_parciales\puesto_Data.csv
../data/raw/glassdoor_parciales\puesto_Software.csv
../data/raw/glassdoor_parciales\puesto_Marketing.csv
../data/raw/glassdoor_parciales\puesto_Administración.csv
../data/raw/glassdoor_parciales\puesto_Finanzas.csv
../data/raw/glassdoor_parciales\puesto_Ingeniería.csv
../data/raw/glassdoor_parciales\puesto_Ventas.csv
../data/raw/glassdoor_parciales\puesto_Logística.csv
../data/raw/glassdoor_parciales\puesto_Hostelería.csv
../data/raw/glassdoor_parciales\puesto_Construcción.csv
../data/raw/glassdoor_parciales\puesto_Educación.csv
../data/raw/glassdoor_parciales\puesto_Recursos-Humanos.csv
../data/raw/glassdoor_parciales\puesto_Legal.csv
../data/raw/glassdoor_parciales\ciudad_Madrid.csv

In [43]:
f = files[0]
df = pd.read_csv(f) 
df.head()

,Titulo,Empresa,Localizacion,Salario,Fecha_Publicacion,Valoracion_Empresa,Descripcion_Completa,Busqueda_Ciudad,Busqueda_Puesto
0,"Carretillero, mozo de almacén",GRUP ALIMENT BARCELONA SA,España,21 mil € - 24 mil € (Proporcionado por la empr...,24 horas,"3,9",Buscamos incorporar un/a Mozo/a de Almacén par...,Barcelona,Todos
1,Director Técnico,Lantus Olimpo,España,33 mil € (Proporcionado por la empresa),24 horas,"3,9","Somos un grupo empresarial, GRUP LANTUS, conso...",Barcelona,Todos
2,Licensed Aircraft Engineer – Base Maintenance,The Emirates Group,Barcelona,No especificado,+ 30 d,"3,9",Licensed Aircraft Engineer – Base Maintenance\...,Barcelona,Todos
3,TECNICO OPERACIONAL DE BRANCH Y TALLER (VEHÍCU...,TIP Group,España,25 mil € - 30 mil € (Proporcionado por la empr...,26 días,"3,9",Somos TIP Group – orgullosos de haber obtenido...,Barcelona,Todos
4,"Corporate Account Executive, Dutch Speaking",CrowdStrike,Barcelona,No especificado,+ 30 d,"3,9","As a global leader in cybersecurity, CrowdStri...",Barcelona,Todos

In [44]:
files[2]

'../data/raw/glassdoor_parciales\\ciudad_Sevilla.csv'

In [45]:
print(files[2].split('\\'))
print(files[2].split('\\')[1])
print(files[2].split('\\')[1].split('_'))
print(files[2].split('\\')[1].split('_')[0]) #este me interesa

print(files[0].split('\\'))
print(files[0].split('\\')[1])
print(files[0].split('\\')[1].split('_'))
print(files[0].split('\\')[1].split('_')[0])

['../data/raw/glassdoor_parciales', 'ciudad_Sevilla.csv']
ciudad_Sevilla.csv
['ciudad', 'Sevilla.csv']
ciudad
['../data/raw/glassdoor_parciales', 'ciudad_Barcelona.csv']
ciudad_Barcelona.csv
['ciudad', 'Barcelona.csv']
ciudad

In [46]:
df = pd.DataFrame()
df_glassdoor = pd.DataFrame() #dataframe vacio para ir llenandolo

for f in files:
    df = pd.read_csv(f)
    categoria = f.split('\\')[1].split('_')[0]

    if categoria == 'ciudad':
        df['Localizacion'] = df['Busqueda_Ciudad']
        df['Sector'] = np.nan
    elif categoria == 'puesto':
        df['Sector'] = df['Busqueda_Puesto']
    else:
        df['Sector'] = np.nan

    df_glassdoor = pd.concat([df,df_glassdoor],axis=0)

In [47]:
df_glassdoor.shape

(27634, 10)

In [48]:
df_glassdoor['Localizacion'].value_counts()

Localizacion
España                  2807
Madrid                  1898
Barcelona               1380
Pamplona                 621
Murcia                   615
                        ...
Viladecavalls              1
Granadilla                 1
Castell-Platja d'Aro       1
Oleiros                    1
Bera                       1
Name: count, Length: 380, dtype: int64

In [49]:
df_glassdoor['Sector'].value_counts()

Sector
Legal               568
Construcción        562
Educación           556
Sanidad             555
Finanzas            551
Hostelería          544
Marketing           540
Recursos Humanos    528
Logística           500
Ingeniería          496
Tecnología          453
Software            450
Data                426
Ventas              374
Administración      195
Name: count, dtype: int64

In [50]:
df_glassdoor[df_glassdoor['Salario'] != 'No especificado']['Salario'].count()

np.int64(4929)

4929 ofertas con el salario especificado.

In [51]:
df_glassdoor.head()

,Titulo,Empresa,Localizacion,Salario,Fecha_Publicacion,Valoracion_Empresa,Descripcion_Completa,Busqueda_Ciudad,Busqueda_Puesto,Sector
0,FISIOTERAPEUTA NEUROLÓGICO,Centro Monte del Pilar,Madrid,24 mil € - 26 mil € (Proporcionado por la empr...,24 horas,"3,9",Oferta de empleo – Fisioterapeuta Neurológico/...,Madrid,Todos,NaN
1,Comercial puerta fría (presencial) - Sector ba...,Total Management Consulting,Madrid,1 mil € - 6 mil € (Proporcionado por la empresa),24 horas,"3,9",Desde Total Management Consulting nos encontra...,Madrid,Todos,NaN
2,Profesora/a de Lengua 2ºESO (Aravaca),Verona Servicios de Intermediación Educativa S.L.,Madrid,"10,00 € - 12,00 € Por hora (Proporcionado por ...",24 horas,"3,9",Estamos seleccionando un profesor/a para impar...,Madrid,Todos,NaN
3,Direct Entry Captain - Pilot,The Emirates Group,Madrid,No especificado,+ 30 d,"3,9",Company Introduction\n\n\nFrom its global hub ...,Madrid,Todos,NaN
4,Promotor/a - Encuestador/a de Educación (Campu...,Cambridge Exams,Madrid,1 mil € (Proporcionado por la empresa),24 horas,"3,9","¿Te consideras una persona extrovertida, empát...",Madrid,Todos,NaN

In [52]:
df_glassdoor.shape

(27634, 10)

In [53]:
df_glassdoor.drop_duplicates(subset=['Descripcion_Completa'], inplace=True)
df_glassdoor.shape

(21069, 10)

In [54]:
df_glassdoor.to_csv('../data/raw/glassdoor.csv', index=False)

In [55]:
df_apify.head()

,title,location,postedTime,publishedAt,companyName,description,applicationsCount,contractType,experienceLevel,workType,sector,salary,companyId
0,"Málaga Cabin Crew Opportunities (Dubai Based, ...",Greater Málaga Metropolitan Area,1 week ago,2026-02-11,Emirates,"Job Purpose\n\nA personality that shines, the ...",59 applicants,Full-time,Associate,"Customer Service, General Business, and Other",Airlines and Aviation and Hospitality,NaN,5042.0
1,Junior Dirección General,"Barcelona, Catalonia, Spain",2 weeks ago,2026-02-03,Catalonia Hotels & Resorts,Si te apasiona el mundo de los viajes y deseas...,Over 200 applicants,Full-time,Associate,Business Development,Hospitality,NaN,74645.0
2,Auxiliar administrativo,"Yaiza, Canary Islands, Spain",1 day ago,2026-02-23,Hoteles Elba | Hotels & Resorts,Desde el Hotel Elba Lanzarote Royal Village Re...,38 applicants,Full-time,Associate,"Customer Service, Human Resources, and Adminis...","Hospitality, Accommodation and Food Services, ...",NaN,2224474.0
3,Profesorado Refuerzo Educativo,"Madrid, Community of Madrid, Spain",2 weeks ago,2026-02-05,JC Madrid Deporte y Cultura SL,Tareas\n\n\nImpartir refuerzo educativo a alum...,30 applicants,Contract,Associate,Education,Education Administration Programs,€9.00/hr - €9.90/hr,2778391.0
4,Autor/a de contenidos eLearning profesional,Spain,4 weeks ago,2026-01-26,ADR Formación,"Buscamos personas apasionadas, comprometidas, ...",Over 200 applicants,Contract,Associate,Education,E-Learning Providers,NaN,2471496.0

In [56]:
df_glassdoor.head()

,Titulo,Empresa,Localizacion,Salario,Fecha_Publicacion,Valoracion_Empresa,Descripcion_Completa,Busqueda_Ciudad,Busqueda_Puesto,Sector
0,FISIOTERAPEUTA NEUROLÓGICO,Centro Monte del Pilar,Madrid,24 mil € - 26 mil € (Proporcionado por la empr...,24 horas,"3,9",Oferta de empleo – Fisioterapeuta Neurológico/...,Madrid,Todos,NaN
1,Comercial puerta fría (presencial) - Sector ba...,Total Management Consulting,Madrid,1 mil € - 6 mil € (Proporcionado por la empresa),24 horas,"3,9",Desde Total Management Consulting nos encontra...,Madrid,Todos,NaN
2,Profesora/a de Lengua 2ºESO (Aravaca),Verona Servicios de Intermediación Educativa S.L.,Madrid,"10,00 € - 12,00 € Por hora (Proporcionado por ...",24 horas,"3,9",Estamos seleccionando un profesor/a para impar...,Madrid,Todos,NaN
3,Direct Entry Captain - Pilot,The Emirates Group,Madrid,No especificado,+ 30 d,"3,9",Company Introduction\n\n\nFrom its global hub ...,Madrid,Todos,NaN
4,Promotor/a - Encuestador/a de Educación (Campu...,Cambridge Exams,Madrid,1 mil € (Proporcionado por la empresa),24 horas,"3,9","¿Te consideras una persona extrovertida, empát...",Madrid,Todos,NaN

In [57]:
df_adzuna = pd.read_csv('../data/raw/AdzunaAPI.csv')
df_adzuna.head()

C:\Users\ivanb\AppData\Local\Temp\ipykernel_34308\2378809938.py:1: DtypeWarning: Columns (0: contract_time, 1: contract_type) have mixed types. Specify dtype option on import or set low_memory=False.
  df_adzuna = pd.read_csv('../data/raw/AdzunaAPI.csv')

,redirect_url,created,description,__CLASS__,salary_max,id,category,title,adref,location,salary_min,company,salary_is_predicted,latitude,longitude,contract_time,contract_type
0,https://www.adzuna.es/details/5477402347?utm_m...,2025-11-02T20:34:24Z,Ofrecemos: empleo bajo condiciones alemanas - ...,Adzuna::API::Response::Job,27600.0,5477402347,"{'tag': 'unknown', '__CLASS__': 'Adzuna::API::...",Cerrajero,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTQ3NzQwMjM0NyIsI...,"{'display_name': 'España', '__CLASS__': 'Adzun...",27600.0,{'__CLASS__': 'Adzuna::API::Response::Company'},0,NaN,NaN,NaN,NaN
1,https://www.adzuna.es/details/5477521584?utm_m...,2025-11-03T00:47:18Z,Te beneficiarás de: contrato laboral holandés ...,Adzuna::API::Response::Job,7560.0,5477521584,{'__CLASS__': 'Adzuna::API::Response::Category...,Instalador de sistemas sanitarios y de calefac...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoibkk3U01TUFU4Qkc4U...,"{'area': ['España'], '__CLASS__': 'Adzuna::API...",7200.0,{'__CLASS__': 'Adzuna::API::Response::Company'},0,NaN,NaN,NaN,NaN
2,https://www.adzuna.es/details/5477402236?utm_m...,2025-11-02T20:34:23Z,Ofrecemos: empleo bajo condiciones belgas – co...,Adzuna::API::Response::Job,47604.0,5477402236,"{'label': 'Unknown', 'tag': 'unknown', '__CLAS...",Conductor CE (Bélgica),eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTQ3NzQwMjIzNiIsI...,"{'area': ['España'], 'display_name': 'España',...",47604.0,{'__CLASS__': 'Adzuna::API::Response::Company'},0,NaN,NaN,NaN,NaN
3,https://www.adzuna.es/details/5501685320?utm_m...,2025-11-18T13:24:29Z,Company: Gridlines Gridlines is a rapidly grow...,Adzuna::API::Response::Job,NaN,5501685320,"{'label': 'Otros trabajos', '__CLASS__': 'Adzu...",Senior Analyst- Model Audit,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTUwMTY4NTMyMCIsI...,{'__CLASS__': 'Adzuna::API::Response::Location...,NaN,{'__CLASS__': 'Adzuna::API::Response::Company'...,0,NaN,NaN,NaN,NaN
4,https://www.adzuna.es/details/5477401159?utm_m...,2025-11-02T20:34:10Z,Ofrecemos: contrato de trabajo austriaco - rel...,Adzuna::API::Response::Job,33600.0,5477401159,"{'label': 'Unknown', '__CLASS__': 'Adzuna::API...",MAG soldador para vehículos blindados,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTQ3NzQwMTE1OSIsI...,{'__CLASS__': 'Adzuna::API::Response::Location...,33600.0,{'__CLASS__': 'Adzuna::API::Response::Company'},0,NaN,NaN,NaN,NaN